# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dataMahasiswa.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import (QWidget, QVBoxLayout, 
     QHBoxLayout, QLineEdit, 
     QPushButton, QListWidget)
from editAction import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(928, 607)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(142, 390, 24, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(141, 430, 39, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(140, 470, 57, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(142, 510, 50, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")

        # line edit NIM
        self.lineEdit_nim = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_nim.setGeometry(QtCore.QRect(220, 390, 381, 20))
        self.lineEdit_nim.setObjectName("lineEdit_nim")

        # line edit Nama
        self.lineEdit_nama = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_nama.setGeometry(QtCore.QRect(220, 430, 381, 20))
        self.lineEdit_nama.setObjectName("lineEdit_nama")

        # line edit Jurusan
        self.lineEdit_jurusan = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_jurusan.setGeometry(QtCore.QRect(220, 470, 381, 20))
        self.lineEdit_jurusan.setObjectName("lineEdit_jurusan")

        # line edit NO Telp
        self.lineEdit_notelp = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_notelp.setGeometry(QtCore.QRect(220, 510, 381, 20))
        self.lineEdit_notelp.setObjectName("lineEdit_notelp")

        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(280, 540, 320, 25))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tambah = QtWidgets.QPushButton(self.layoutWidget)

        # Button Tambah
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tambah.setFont(font)
        self.tambah.setObjectName("tambah")
        self.horizontalLayout.addWidget(self.tambah)
        self.edit = QtWidgets.QPushButton(self.layoutWidget)

        # Button Edit
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.edit.setFont(font)
        self.edit.setObjectName("edit")
        self.horizontalLayout.addWidget(self.edit)
        self.clear = QtWidgets.QPushButton(self.layoutWidget)

        # Button Clear
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.clear.setFont(font)
        self.clear.setObjectName("clear")
        self.horizontalLayout.addWidget(self.clear)
        self.hapus = QtWidgets.QPushButton(self.layoutWidget)

        # Button Hapus
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.hapus.setFont(font)
        self.hapus.setObjectName("hapus")
        self.horizontalLayout.addWidget(self.hapus)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(140, 31, 491, 331))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.hasil = QtWidgets.QListWidget(self.widget)
        self.hasil.setObjectName("hasil")
        self.verticalLayout.addWidget(self.hasil)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 928, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        # Function
        self.tambah.clicked.connect(self.addButtonClick)
        self.edit.clicked.connect(self.editButtonClick)
        self.clear.clicked.connect(self.hasil.clear)
        self.hapus.clicked.connect(self.deleteButtonClick)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    # Add Button Click
    def addButtonClick(self):
        self.hasil.addItem(
            self.lineEdit_nim.text() + ' - ' +
            self.lineEdit_nama.text() + ' - ' +
            self.lineEdit_jurusan.text() + ' - ' +
            self.lineEdit_notelp.text()
        )
    
    # Delete Button Click
    def deleteButtonClick(self):
        row = self.hasil.currentRow()
        if row >= 0 :
            self.hasil.takeItem(row)

    # Edit Button Click
    def editButtonClick(self):
        if self.hasil.currentRow() < 0: return
        self.entryForm = EntryForm()
        s = str(self.hasil.currentItem().text())
        idx = s.index('-')
        self.entryForm.nim.setText(s[:(idx-1)])
        self.entryForm.nama.setText(s[(idx-2):])
        self.entryForm.jurusan.setText(s[(idx-3):])
        self.entryForm.telp.setText(s[(idx-4):])

        if self.entryForm.exec_() == QDialog.Accepted:
           self.hasil.currentItem().setText(
           self.entryForm.nim.text() + ' - ' +
           self.entryForm.nama.text() + ' - ' +
           self.entryForm.jurusan.text() + ' - ' +
           self.entryForm.telp.text())

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "NIM"))
        self.label_3.setText(_translate("MainWindow", "Nama"))
        self.label_4.setText(_translate("MainWindow", "Jurusan"))
        self.label_5.setText(_translate("MainWindow", "No. Telp"))
        self.tambah.setText(_translate("MainWindow", "TAMBAH"))
        self.edit.setText(_translate("MainWindow", "EDIT"))
        self.clear.setText(_translate("MainWindow", "CLEAR"))
        self.hapus.setText(_translate("MainWindow", "HAPUS"))
        self.label.setText(_translate("MainWindow", "DATA MAHASISWA"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
